In [1]:
import pandas as pd

In [23]:
# step 1 (Reading csv file and printing it)
df=pd.read_csv("shorts.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",NaN,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",NaN,C-5███ NU███ JE█████████LTD███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.0,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,NaN,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
5,13695234,HRX by Hrithik Roshan,"HRX By Hrithik Roshan Women Medieval Blue,Wild...",4.4,150,1499.0,30.0,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":5,""2_stars"":5,""3_stars"":15,""4_stars""...",NaN,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13695234_cae700"",""https://videos.myntasse...","11t███loo███Fla█████████6, ███████████████████...",NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
6,13610026,HRX by Hrithik Roshan,HRX By Hrithik Roshan Men Black Forest & Golde...,4.2,84,1899.0,40.0,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":6,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13610026_cae700""]","11t███loo███Fla█████████6, ███████████████████...",NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
7,16051700,Miaz Lifestyle,Women White Set Of 2 Biker Shorts,0.0,0,1999.0,52.0,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
8,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",NaN,180███ Bh███ Wa█████████ Co███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
9,16051704,Miaz Lifestyle,Women Pack Of 2 Beige & White Sports Shorts,0.0,0,1999.0,71.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
10,14494548,CUTECUMBER,Girls Pack Of 2 Printed Mid-Rise Regular Shorts,4.3,11,650.0,NaN,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",NaN,E -███SEC███ A █████████RAN███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
11,14496210,CUTECUMBER,Girls Pack of 2 Floral Printed Mid-Rise Regula...,4.6,46,650.0,NaN,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",NaN,E -███SEC███ A █████████RAN███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
12,16043840,BRINNS,Women Dark Grey Solid Mid Rise Regular Shorts,0.0,0,1699.0,60.0,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BRI███ RE███L L███,"[{""size"":""26"",""value"":""36.0in"",""value_name"":""H...",NaN,"Bas███nt ███or,█████████har███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
13,18942852,FITINC,Women Blue Skinny Fit High-Rise Training or Gy...,4.4,14,999.0,55.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fit███ Ap███els█████████Lim██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,"GRO███ FL███, K█████████2, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
14,18650484,CLUB A9,Women Pink Floral Printed Shorts,4.5,14,699.0,54.0,"""₹321.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,ADI███ AP███ELS███,"[{""size"":""30"",""value"":""36.0in"",""value_name"":""H...",NaN,"56/███ire███oy █████████, B███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
15,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695.0,40.0,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,C/o███s G███cus█████████hai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.0,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,"3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.0,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",NaN,"11t███loo███Fla█████████6, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",NaN,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.0,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts

In [24]:
#step 2 (head/tail,shape,columns,datatypes)

df.shape

(21, 24)

In [25]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",NaN,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",NaN,C-5███ NU███ JE█████████LTD███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.0,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,NaN,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts

In [26]:
df.head(7)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",NaN,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",NaN,C-5███ NU███ JE█████████LTD███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.0,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,NaN,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
5,13695234,HRX by Hrithik Roshan,"HRX By Hrithik Roshan Women Medieval Blue,Wild...",4.4,150,1499.0,30.0,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":5,""2_stars"":5,""3_stars"":15,""4_stars""...",NaN,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13695234_cae700"",""https://videos.myntasse...","11t███loo███Fla█████████6, ███████████████████...",NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
6,13610026,HRX by Hrithik Roshan,HRX By Hrithik Roshan Men Black Forest & Golde...,4.2,84,1899.0,40.0,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":6,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13610026_cae700""]","11t███loo███Fla█████████6, ███████████████████...",NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts

In [27]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.0,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,"3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.0,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",NaN,"11t███loo███Fla█████████6, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",NaN,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.0,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts

In [28]:
df.tail(6)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
15,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695.0,40.0,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,C/o███s G███cus█████████hai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.0,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,"3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.0,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",NaN,"11t███loo███Fla█████████6, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",NaN,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.0,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts

In [29]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [30]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [31]:
print(type(df["title"]))
print(type(df["rating"]))
print(type(df["seller_name"]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [47]:
#step3 Identify nullvalues and deal with it

df.isnull().sum()

In [35]:
df.fillna(df["initial_price"].mean(),inplace=True)
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.000000,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",1617.761905,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.000000,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",1617.761905,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",1617.761905,C-5███ NU███ JE█████████LTD███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",1617.761905,Blo███B-1███abi█████████-24███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,1617.761905,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":22,""4_stars...",1617.761905,1617.761905,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",1617.761905,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.000000,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",1617.761905,1617.761905,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",1617.761905,1617.761905,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
5,13695234,HRX by Hrithik Roshan,"HRX By Hrithik Roshan Women Medieval Blue,Wild...",4.4,150,1499.0,30.000000,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":5,""2_stars"":5,""3_stars"":15,""4_stars""...",1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13695234_cae700"",""https://videos.myntasse...","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
6,13610026,HRX by Hrithik Roshan,HRX By Hrithik Roshan Men Black Forest & Golde...,4.2,84,1899.0,40.000000,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":6,""4_stars"":...",1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13610026_cae700""]","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
7,16051700,Miaz Lifestyle,Women White Set Of 2 Biker Shorts,0.0,0,1999.0,52.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
8,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299.0,50.000000,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",1617.761905,180███ Bh███ Wa█████████ Co███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
9,16051704,Miaz Lifestyle,Women Pack Of 2 Beige & White Sports Shorts,0.0,0,1999.0,71.000000,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
10,14494548,CUTECUMBER,Girls Pack Of 2 Printed Mid-Rise Regular Shorts,4.3,11,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
11,14496210,CUTECUMBER,Girls Pack of 2 Floral Printed Mid-Rise Regula...,4.6,46,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
12,16043840,BRINNS,Women Dark Grey Solid Mid Rise Regular Shorts,0.0,0,1699.0,60.000000,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/160...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,BRI███ RE███L L███,"[{""size"":""26"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"Bas███nt ███or,█████████har███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
13,18942852,FITINC,Women Blue Skinny Fit High-Rise Training or Gy...,4.4,14,999.0,55.000000,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Fit███ Ap███els█████████Lim██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"GRO███ FL███, K█████████2, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
14,18650484,CLUB A9,Women Pink Floral Printed Shorts,4.5,14,699.0,54.000000,"""₹321.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",1617.761905,ADI███ AP███ELS███,"[{""size"":""30"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"56/███ire███oy █████████, B███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
15,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695.0,40.000000,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",1617.761905,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,C/o███s G███cus█████████hai███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.000000,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",1617.761905,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,Plo███o- ███ 1s█████████Sui███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.000000,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",1617.761905,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,"3rd███165███th █████████, s███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.000000,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",1617.761905,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",1617.761905,"11t███loo███Fla█████████6, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.000000,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...",1617.761905,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",1617.761905,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.000000,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",1617.761905,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"Gro███ Fl███, N█████████old███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts

In [36]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [41]:
#step 4 Filter rows 

filter_rows=df[df["initial_price"]>1000]
print(filter_rows)

    product_id                  title  \
0     18947596              KASSUALLY
1     18946864             Cub McPaws
2     18921438          Gini and Jony
3     13624708                   Nike
5     13695234  HRX by Hrithik Roshan
6     13610026  HRX by Hrithik Roshan
7     16051700         Miaz Lifestyle
8     14561272                  ASICS
9     16051704         Miaz Lifestyle
12    16043840                 BRINNS
15    19024468            Blackberrys
16    17333612           UNDER ARMOUR
17    17332648         Tommy Hilfiger
18    15177608  HRX by Hrithik Roshan
19    18947600              KASSUALLY
20    18658050            Allen Solly

                                  product_description  rating  ratings_count  \
0     Women Green Slim Fit Denim Outdoor Denim Shorts     4.7              9
1                         Girls Yellow Printed Shorts     4.5             20
2                     Boys Black Denim Outdoor Shorts     4.6             28
3   Men Black Solid Standard Fit CHALLENGER DRI FI...     4.4            376
5   HRX By Hrithik Roshan Women Medieval Blue,Wild...     4.4            150
6   HRX By Hrithik Roshan Men Black Forest & Golde...     4.2             84
7                   Women White Set Of 2 Biker Shorts     0.0              0
8   Court M 7In   Men Black Solid Mid-Rise Tennis ...     5.0              5
9         Women Pack Of 2 Beige & White Sports Shorts     0.0              0
12      Women Dark Grey Solid Mid Rise Regular Shorts     0.0              0
15            Men Pure Cotton Printed Slim Fit Shorts     4.1              9
16  Women Mustard Yellow Play Up 3.0 Colourblocked...     3.6             10
17         Women Red & Navy Blue Printed Chino Shorts     4.7              9
18                                  Boys Green Shorts     4.5             61
19  Women White Printed Slim Fit High-Rise Denim O...     4.7             38
20                  Men Brown Printed Slim Fit Shorts     4.6             13

    initial_price     discount  final_price currency  \
0          1799.0    67.000000    "₹593.00"      INR
1          1499.0    53.000000    "₹699.00"      INR
2          1599.0    25.000000    "₹959.00"      INR
3          1795.0  1617.761905  "₹1,795.00"      INR
5          1499.0    30.000000  "₹1,049.00"      INR
6          1899.0    40.000000  "₹1,139.00"      INR
7          1999.0    52.000000    "₹959.00"      INR
8          2299.0    50.000000  "₹1,149.00"      INR
9          1999.0    71.000000    "₹579.00"      INR
12         1699.0    60.000000    "₹679.00"      INR
15         1695.0    40.000000  "₹1,017.00"      INR
16         2499.0    25.000000  "₹1,874.00"      INR
17         2999.0    40.000000  "₹1,499.00"      INR
18         1399.0    30.000000    "₹979.00"      INR
19         1899.0    66.000000    "₹645.00"      INR
20         1799.0    40.000000  "₹1,079.00"      INR

                                               images  ...  \
0   http://assets.myntassets.com/assets/images/189...  ...
1   http://assets.myntassets.com/assets/images/189...  ...
2   http://assets.myntassets.com/assets/images/189...  ...
3   http://assets.myntassets.com/assets/images/136...  ...
5   http://assets.myntassets.com/assets/images/136...  ...
6   http://assets.myntassets.com/assets/images/136...  ...
7   http://assets.myntassets.com/assets/images/160...  ...
8   http://assets.myntassets.com/assets/images/pro...  ...
9   http://assets.myntassets.com/assets/images/160...  ...
12  http://assets.myntassets.com/assets/images/160...  ...
15  http://assets.myntassets.com/assets/images/190...  ...
16  http://assets.myntassets.com/assets/images/173...  ...
17  http://assets.myntassets.com/assets/images/173...  ...
18  http://assets.myntassets.com/assets/images/151...  ...
19  http://assets.myntassets.com/assets/images/189...  ...
20  http://assets.myntassets.com/assets/images/186...  ...

                                      amount_of_stars what_customers_said  \
0   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
1   {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...         1617.761905
2   {"1_star":1,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
3   {"1_star":22,"2_stars":8,"3_stars":22,"4_stars...         1617.761905
5   {"1_star":5,"2_stars":5,"3_stars":15,"4_stars"...         1617.761905
6   {"1_star":7,"2_stars":3,"3_stars":6,"4_stars":...         1617.761905
7   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
8   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
9   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
12  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
15  {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...         1617.761905
16  {"1_star":2,"2_stars":2,"3_stars":0,"4_stars":...         1617.761905
17  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...         1617.761905
18  {"1_star":3,"2_stars":1,"3_stars":2,"4_stars":...         1617.761905
19  {"1_star":0,"2_stars":2,"3_stars":0,"4_stars":...         1617.761905
20  {"1_star":0,"2_stars":0,"3_stars":2,"4_stars":...         1617.761905

                          seller_name  \
0                  Khu███r A███arl███
1            Poc███uch███Kid█████████
2                        Ret███Net███
3                         1617.761905
5                  Omn███ch ███ail███
6                  Omn███ch ███ail███
7                      Mia███ife███le
8                        Spo███ IQ███
9                      Mia███ife███le
12                 BRI███ RE███L L███
15     Moh███Clo███ng █████████Ltd███
16                       Sup███om ███
17                 Fla███ech███tai███
18                 Omn███ch ███ail███
19           Khu███r A███arl█████████
20  Wes███ry ███din█████████d_M██████

                                                sizes  \
0   [{"size":"26","value":"31.5in","value_name":"H...
1   [{"size":"4-5Y","value":"19.75in","value_name"...
2   [{"size":"3-4Y","value":"17.0in","value_name":...
3   [{"size":"28","value":"28.0in","value_name":"T...
5   [{"size":"26","value":"26.0in","value_name":"T...
6   [{"size":"26","value":"26.0in","value_name":"T...
7   [{"size":"28","value":"28.0in","value_name":"T...
8   [{"size":"27","value":"27.0in","value_name":"T...
9   [{"size":"28","value":"28.0in","value_name":"T...
12  [{"size":"26","value":"36.0in","value_name":"H...
15  [{"size":"28","value":"28.0in","value_name":"T...
16  [{"size":"26","value":"26.0in","value_name":"T...
17  [{"size":"26","value":"26.0in","value_name":"T...
18  [{"size":"8-9Y","value":"22.75in","value_name"...
19  [{"size":"26","value":"30.5in","value_name":"H...
20  [{"size":"28","value":"28.0in","value_name":"T...

                                               videos  \
0                                         1617.761905
1                                         1617.761905
2                                         1617.761905
3   ["https://videos.myntassets.com/assets/videos/...
5   ["rw-13695234_cae700","https://videos.myntasse...
6                              ["rw-13610026_cae700"]
7                                         1617.761905
8                                         1617.761905
9                                         1617.761905
12                                        1617.761905
15                                        1617.761905
16                                        1617.761905
17                                        1617.761905
18                                        1617.761905
19                                        1617.761905
20                                        1617.761905

                                   seller_information  \
0   2- ███OR,███-22█████████PLE███████████████████...
1   C-5███ NU███ JE█████████LTD███████████████████...
2   Blo███B-1███abi█████████-24███████████████████...
3                                         1617.761905
5   11t███loo███Fla█████████6, ███████████████████...
6   11t███loo███Fla█████████6, ███████████████████...
7       B-4███ubh███ Kh█████████lhi██████████████████
8   180███ Bh███ Wa█████████ Co███████████████████...
9       B-4███ubh███ Kh█████████lhi██████████████████
12  Bas███nt ███or,█████████har███████████████████...
15  C/o███s G███cus█████████hai███████████████████...
16  Plo███o- ███ 1s█████████Sui███████████████████...
17  3rd███165███th █████████, s███████████████████...
18  11t███loo███Fla█████████6, ███████████████████...
19  KHA███ NO███85/█████████Vih███████████████████...
20  Gro███ Fl███, N█████████old███████████████████...

                               variations  \
0                                    [{}]
1                             1617.761905
2                             1617.761905
3                                    [{}]
5                             1617.761905
6                             1617.761905
7                     [{},{},{},{},{},{}]
8                             1617.761905
9                     [{},{},{},{},{},{}]
12  [{},{},{},{},{},{},{},{},{},{},{},{}]
15                            1617.761905
16                            1617.761905
17                            1617.761905
18                            1617.761905
19                                   [{}]
20                            1617.761905

                                           best_offer  \
0   {"applicable_on":"Orders above Rs. 649 (only o...
1   {"applicable_on":"Orders above Rs. 999 (only o...
2   {"applicable_on":"Orders above Rs. 999 (only o...
3                                                  {}
5                                                  {}
6                                                  {}
7   {"applicable_on":"Orders above Rs. 999 (only o...
8   {"applicable_on":"Orders above Rs. 1499 (only ...
9   {"applicable_on":"Orders above Rs. 649 (only o...
12  {"applicable_on":"Orders above Rs. 999 (only o...
15  {"applicable_on":"Orders above Rs. 999 (only o...
16  {"applicable_on":"Orders above Rs. 1499 (only ...
17  {"applicable_on":"Orders above Rs. 1499 (only ...
18  {"applicable_on":"Orders above Rs. 1099 (only ...
19  {"applicable_on":"Orders above Rs. 649 (only o...
20  {"applicable_on":"Orders above Rs. 999 (only o...

                                          more_offers category
0   [{"offer_name":"10% Instant Discount on IndusI...   shorts
1   [{"offer_name":"10% Instant Discount on IndusI...   shorts
2   [{"offer_name":"10% Instant Discount on IndusI...   shorts
3   [{"offer_name":"10% Instant Discount on Citi C...   shorts
5   [{"offer_name":"10% Instant Discount on Citi C...   shorts
6   [{"offer_name":"10% Instant Discount on Citi C...   shorts
7   [{"offer_name":"10% Instant Discount on IndusI...   shorts
8   [{"offer_name":"10% Instant Discount on IndusI...   shorts
9   [{"offer_name":"10% Instant Discount on IndusI...   shorts
12  [{"offer_name":"10% Instant Discount on IndusI...   shorts
15  [{"offer_name":"10% Instant Discount on IndusI...   shorts
16  [{"offer_name":"10% Instant Discount on IndusI...   shorts
17  [{"offer_name":"10% Instant Discount on IndusI...   shorts
18  [{"offer_name":"10% Instant Discount on IndusI...   shorts
19  [{"offer_name":"10% Instant Discount on IndusI...   shorts
20  [{"offer_name":"10% Instant Discount on IndusI...   shorts

[16 rows x 24 columns]

In [42]:
#selecting columns

df[["title","product_description"]]

                    title                                product_description
0               KASSUALLY    Women Green Slim Fit Denim Outdoor Denim Shorts
1              Cub McPaws                        Girls Yellow Printed Shorts
2           Gini and Jony                    Boys Black Denim Outdoor Shorts
3                    Nike  Men Black Solid Standard Fit CHALLENGER DRI FI...
4                  DChica    Girls Black Skinny Fit High-Rise Cycling Shorts
5   HRX by Hrithik Roshan  HRX By Hrithik Roshan Women Medieval Blue,Wild...
6   HRX by Hrithik Roshan  HRX By Hrithik Roshan Men Black Forest & Golde...
7          Miaz Lifestyle                  Women White Set Of 2 Biker Shorts
8                   ASICS  Court M 7In   Men Black Solid Mid-Rise Tennis ...
9          Miaz Lifestyle        Women Pack Of 2 Beige & White Sports Shorts
10             CUTECUMBER    Girls Pack Of 2 Printed Mid-Rise Regular Shorts
11             CUTECUMBER  Girls Pack of 2 Floral Printed Mid-Rise Regula...
12                 BRINNS      Women Dark Grey Solid Mid Rise Regular Shorts
13                 FITINC  Women Blue Skinny Fit High-Rise Training or Gy...
14                CLUB A9                   Women Pink Floral Printed Shorts
15            Blackberrys            Men Pure Cotton Printed Slim Fit Shorts
16           UNDER ARMOUR  Women Mustard Yellow Play Up 3.0 Colourblocked...
17         Tommy Hilfiger         Women Red & Navy Blue Printed Chino Shorts
18  HRX by Hrithik Roshan                                  Boys Green Shorts
19              KASSUALLY  Women White Printed Slim Fit High-Rise Denim O...
20            Allen Solly                  Men Brown Printed Slim Fit Shorts

In [43]:
df[["rating","initial_price","title"]]

    rating  initial_price                  title
0      4.7         1799.0              KASSUALLY
1      4.5         1499.0             Cub McPaws
2      4.6         1599.0          Gini and Jony
3      4.4         1795.0                   Nike
4      4.3          599.0                 DChica
5      4.4         1499.0  HRX by Hrithik Roshan
6      4.2         1899.0  HRX by Hrithik Roshan
7      0.0         1999.0         Miaz Lifestyle
8      5.0         2299.0                  ASICS
9      0.0         1999.0         Miaz Lifestyle
10     4.3          650.0             CUTECUMBER
11     4.6          650.0             CUTECUMBER
12     0.0         1699.0                 BRINNS
13     4.4          999.0                 FITINC
14     4.5          699.0                CLUB A9
15     4.1         1695.0            Blackberrys
16     3.6         2499.0           UNDER ARMOUR
17     4.7         2999.0         Tommy Hilfiger
18     4.5         1399.0  HRX by Hrithik Roshan
19     4.7         1899.0              KASSUALLY
20     4.6         1799.0            Allen Solly

In [44]:
df["total_amount"]=df["initial_price"]*df["rating"]

In [45]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.000000,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",1617.761905,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8455.3
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.000000,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",1617.761905,C-5███ NU███ JE█████████LTD███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6745.5
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",1617.761905,Blo███B-1███abi█████████-24███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,7355.4
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,1617.761905,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,1617.761905,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",1617.761905,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,7898.0
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.000000,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,1617.761905,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",1617.761905,1617.761905,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,2575.7
5,13695234,HRX by Hrithik Roshan,"HRX By Hrithik Roshan Women Medieval Blue,Wild...",4.4,150,1499.0,30.000000,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13695234_cae700"",""https://videos.myntasse...","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,6595.6
6,13610026,HRX by Hrithik Roshan,HRX By Hrithik Roshan Men Black Forest & Golde...,4.2,84,1899.0,40.000000,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13610026_cae700""]","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,7975.8
7,16051700,Miaz Lifestyle,Women White Set Of 2 Biker Shorts,0.0,0,1999.0,52.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
8,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299.0,50.000000,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",1617.761905,180███ Bh███ Wa█████████ Co███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,11495.0
9,16051704,Miaz Lifestyle,Women Pack Of 2 Beige & White Sports Shorts,0.0,0,1999.0,71.000000,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
10,14494548,CUTECUMBER,Girls Pack Of 2 Printed Mid-Rise Regular Shorts,4.3,11,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,2795.0
11,14496210,CUTECUMBER,Girls Pack of 2 Floral Printed Mid-Rise Regula...,4.6,46,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,2990.0
12,16043840,BRINNS,Women Dark Grey Solid Mid Rise Regular Shorts,0.0,0,1699.0,60.000000,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,BRI███ RE███L L███,"[{""size"":""26"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"Bas███nt ███or,█████████har███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
13,18942852,FITINC,Women Blue Skinny Fit High-Rise Training or Gy...,4.4,14,999.0,55.000000,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Fit███ Ap███els█████████Lim██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"GRO███ FL███, K█████████2, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,4395.6
14,18650484,CLUB A9,Women Pink Floral Printed Shorts,4.5,14,699.0,54.000000,"""₹321.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,ADI███ AP███ELS███,"[{""size"":""30"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"56/███ire███oy █████████, B███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,3145.5
15,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695.0,40.000000,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,1617.761905,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,C/o███s G███cus█████████hai███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6949.5
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.000000,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,1617.761905,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,Plo███o- ███ 1s█████████Sui███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8996.4
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.000000,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,1617.761905,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,"3rd███165███th █████████, s███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,14095.3
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.000000,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",1617.761905,"11t███loo███Fla█████████6, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6295.5
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.000000,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",1617.761905,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8925.3
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.000000,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"Gro███ Fl███, N█████████old███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8275.4

In [48]:
#step 5 remove duplicates 

df=df.drop_duplicates()
print("Duplicates removed")

Duplicates removed

In [49]:
#step 6 Creating new column from existting ones 

df["total_amount"] = df["initial_price"] * df["rating"]

df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799.0,67.000000,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...",1617.761905,"2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8455.3
1,18946864,Cub McPaws,Girls Yellow Printed Shorts,4.5,20,1499.0,53.000000,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Poc███uch███Kid█████████,"[{""size"":""4-5Y"",""value"":""19.75in"",""value_name""...",1617.761905,C-5███ NU███ JE█████████LTD███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6745.5
2,18921438,Gini and Jony,Boys Black Denim Outdoor Shorts,4.6,28,1599.0,25.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Ret███Net███,"[{""size"":""3-4Y"",""value"":""17.0in"",""value_name"":...",1617.761905,Blo███B-1███abi█████████-24███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,7355.4
3,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795.0,1617.761905,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,1617.761905,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",1617.761905,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,7898.0
4,18645102,DChica,Girls Black Skinny Fit High-Rise Cycling Shorts,4.3,16,599.0,53.000000,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,1617.761905,"[{""size"":""8-10Y"",""value"":""29.0in"",""value_name""...",1617.761905,1617.761905,"[{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,2575.7
5,13695234,HRX by Hrithik Roshan,"HRX By Hrithik Roshan Women Medieval Blue,Wild...",4.4,150,1499.0,30.000000,"""₹1,049.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13695234_cae700"",""https://videos.myntasse...","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,6595.6
6,13610026,HRX by Hrithik Roshan,HRX By Hrithik Roshan Men Black Forest & Golde...,4.2,84,1899.0,40.000000,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/136...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-13610026_cae700""]","11t███loo███Fla█████████6, ███████████████████...",1617.761905,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts,7975.8
7,16051700,Miaz Lifestyle,Women White Set Of 2 Biker Shorts,0.0,0,1999.0,52.000000,"""₹959.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
8,14561272,ASICS,Court M 7In Men Black Solid Mid-Rise Tennis ...,5.0,5,2299.0,50.000000,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,Spo███ IQ███,"[{""size"":""27"",""value"":""27.0in"",""value_name"":""T...",1617.761905,180███ Bh███ Wa█████████ Co███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,11495.0
9,16051704,Miaz Lifestyle,Women Pack Of 2 Beige & White Sports Shorts,0.0,0,1999.0,71.000000,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,Mia███ife███le,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,B-4███ubh███ Kh█████████lhi██████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
10,14494548,CUTECUMBER,Girls Pack Of 2 Printed Mid-Rise Regular Shorts,4.3,11,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,2795.0
11,14496210,CUTECUMBER,Girls Pack of 2 Floral Printed Mid-Rise Regula...,4.6,46,650.0,1617.761905,"""₹650.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1617.761905,CUT███MBE███ESI█████████TD,"[{""size"":""12-18M"",""value"":""25.98in"",""value_nam...",1617.761905,E -███SEC███ A █████████RAN███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,2990.0
12,16043840,BRINNS,Women Dark Grey Solid Mid Rise Regular Shorts,0.0,0,1699.0,60.000000,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/160...,...,1617.761905,BRI███ RE███L L███,"[{""size"":""26"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"Bas███nt ███or,█████████har███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,0.0
13,18942852,FITINC,Women Blue Skinny Fit High-Rise Training or Gy...,4.4,14,999.0,55.000000,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Fit███ Ap███els█████████Lim██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"GRO███ FL███, K█████████2, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,4395.6
14,18650484,CLUB A9,Women Pink Floral Printed Shorts,4.5,14,699.0,54.000000,"""₹321.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,ADI███ AP███ELS███,"[{""size"":""30"",""value"":""36.0in"",""value_name"":""H...",1617.761905,"56/███ire███oy █████████, B███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,3145.5
15,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695.0,40.000000,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,1617.761905,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,C/o███s G███cus█████████hai███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6949.5
16,17333612,UNDER ARMOUR,Women Mustard Yellow Play Up 3.0 Colourblocked...,3.6,10,2499.0,25.000000,"""₹1,874.00""",INR,http://assets.myntassets.com/assets/images/173...,...,1617.761905,Sup███om ███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,Plo███o- ███ 1s█████████Sui███████████████████...,1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8996.4
17,17332648,Tommy Hilfiger,Women Red & Navy Blue Printed Chino Shorts,4.7,9,2999.0,40.000000,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/173...,...,1617.761905,Fla███ech███tai███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",1617.761905,"3rd███165███th █████████, s███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,14095.3
18,15177608,HRX by Hrithik Roshan,Boys Green Shorts,4.5,61,1399.0,30.000000,"""₹979.00""",INR,http://assets.myntassets.com/assets/images/151...,...,1617.761905,Omn███ch ███ail███,"[{""size"":""8-9Y"",""value"":""22.75in"",""value_name""...",1617.761905,"11t███loo███Fla█████████6, ███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,6295.5
19,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899.0,66.000000,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,1617.761905,Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",1617.761905,KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8925.3
20,18658050,Allen Solly,Men Brown Printed Slim Fit Shorts,4.6,13,1799.0,40.000000,"""₹1,079.00""",INR,http://assets.myntassets.com/assets/images/186...,...,1617.761905,Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",1617.761905,"Gro███ Fl███, N█████████old███████████████████...",1617.761905,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts,8275.4

In [50]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'total_amount'],
      dtype='object')

In [53]:
df.to_csv("updated.csv",index=False)