In [21]:
# step 1 .Load dataset
import pandas as pd
import sqlite3

In [22]:
df = pd.read_csv('heels.csv')

In [23]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,13474452,Allen Solly,Women Tan Brown & Black Solid Block Heels,4.3,14,2299.0,50.0,"""₹2,299.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",NaN,"[{""size"":""36"",""value"":""22.5cm"",""value_name"":""T...","[""rw-13474452_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
1,17647418,FOOTONS,Women Beige Comfort Sandals,5.0,2,3199.0,55.0,"""₹3,199.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""36"",""value"":""21.0cm"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
2,18596612,Brauch,Grey Colourblocked Block Peep Toes with Buckles,0.0,0,999.0,62.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bra███ En███pri██████,"[{""size"":""36"",""value"":""22.0cm"",""value_name"":""T...",NaN,B-1███ BF███Pus█████████Enc███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",heels
3,13475738,TRASE,Women Brown Laser Cut Wedges,4.0,39,1599.0,NaN,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":3,""3_stars"":5,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""36"",""value"":""22.0cm"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
4,22217088,DressBerry,Open Back Flatform Heels,4.1,34,1599.0,54.0,"""₹735.00""",INR,http://assets.myntassets.com/assets/images/222...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",KIR███ENT███RIS███,"[{""size"":""36"",""value"":""23.2cm"",""value_name"":""T...",NaN,LOW███GRO███ FL█████████ERT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",heels

In [24]:
conn = sqlite3.connect('heels_sales.db')

In [25]:
df.to_sql('heels', conn, if_exists='replace', index=False)

9

In [28]:
# step 2  schema
query = "PRAGMA table_info(heels);"
pd.read_sql(query, conn)

    cid                    name     type  notnull dflt_value  pk
0     0              product_id  INTEGER        0       None   0
1     1                   title     TEXT        0       None   0
2     2     product_description     TEXT        0       None   0
3     3                  rating     REAL        0       None   0
4     4           ratings_count  INTEGER        0       None   0
5     5           initial_price     REAL        0       None   0
6     6                discount     REAL        0       None   0
7     7             final_price     TEXT        0       None   0
8     8                currency     TEXT        0       None   0
9     9                  images     TEXT        0       None   0
10   10        delivery_options     TEXT        0       None   0
11   11         product_details     TEXT        0       None   0
12   12             breadcrumbs     TEXT        0       None   0
13   13  product_specifications     TEXT        0       None   0
14   14         amount_of_stars     TEXT        0       None   0
15   15     what_customers_said     TEXT        0       None   0
16   16             seller_name     TEXT        0       None   0
17   17                   sizes     TEXT        0       None   0
18   18                  videos     TEXT        0       None   0
19   19      seller_information     TEXT        0       None   0
20   20              variations     TEXT        0       None   0
21   21              best_offer     TEXT        0       None   0
22   22             more_offers     TEXT        0       None   0
23   23                category     TEXT        0       None   0

In [29]:
 # step 2 sample data 
query = "SELECT * FROM heels LIMIT 5"
pd.read_sql(query, conn)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,13474452,Allen Solly,Women Tan Brown & Black Solid Block Heels,4.3,14,2299.0,50.0,"""₹2,299.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",None,"[{""size"":""36"",""value"":""22.5cm"",""value_name"":""T...","[""rw-13474452_cae700"",""https://videos.myntasse...",None,None,{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
1,17647418,FOOTONS,Women Beige Comfort Sandals,5.0,2,3199.0,55.0,"""₹3,199.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",None,"[{""size"":""36"",""value"":""21.0cm"",""value_name"":""T...",None,None,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
2,18596612,Brauch,Grey Colourblocked Block Peep Toes with Buckles,0.0,0,999.0,62.0,"""₹379.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",None,Bra███ En███pri██████,"[{""size"":""36"",""value"":""22.0cm"",""value_name"":""T...",None,B-1███ BF███Pus█████████Enc███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",heels
3,13475738,TRASE,Women Brown Laser Cut Wedges,4.0,39,1599.0,NaN,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":3,""3_stars"":5,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",None,"[{""size"":""36"",""value"":""22.0cm"",""value_name"":""T...",None,None,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",heels
4,22217088,DressBerry,Open Back Flatform Heels,4.1,34,1599.0,54.0,"""₹735.00""",INR,http://assets.myntassets.com/assets/images/222...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",KIR███ENT███RIS███,"[{""size"":""36"",""value"":""23.2cm"",""value_name"":""T...",None,LOW███GRO███ FL█████████ERT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",heels

In [30]:

query="SELECT COUNT(*) AS total_rows FROM heels";
pd.read_sql(query, conn)

   total_rows
0           9

In [49]:
query="SELECT category, COUNT(*) AS product_count FROM heels GROUP BY category";
pd.read_sql(query, conn)

  category  product_count
0    heels              9

In [31]:
# # step 3 .Apply WHERE filters (rating)
query="SELECT product_id, title, rating  FROM heels  WHERE rating > 4";
pd.read_sql(query, conn)

   product_id        title  rating
0    13474452  Allen Solly     4.3
1    17647418      FOOTONS     5.0
2    22217088   DressBerry     4.1
3    19217010        Inc 5     4.4

In [32]:
# discount
query="SELECT title, discount FROM heels WHERE discount > 50";
pd.read_sql(query, conn)

           title  discount
0        FOOTONS      55.0
1         Brauch      62.0
2     DressBerry      54.0
3  Bruno Manetti      63.0
4  Bruno Manetti      65.0
5          Anouk      60.0

In [33]:
# category
query="SELECT title, category FROM heels WHERE category = 'heels'";
pd.read_sql(query, conn)

           title category
0    Allen Solly    heels
1        FOOTONS    heels
2         Brauch    heels
3          TRASE    heels
4     DressBerry    heels
5  Bruno Manetti    heels
6          Inc 5    heels
7  Bruno Manetti    heels
8          Anouk    heels

In [35]:
#initial price
query="SELECT title, initial_price  FROM heels WHERE initial_price > 3000";
pd.read_sql(query, conn)

           title  initial_price
0        FOOTONS         3199.0
1  Bruno Manetti         3999.0
2  Bruno Manetti         3999.0

In [36]:
# step 4 aggregations 
query="SELECT AVG(rating) AS average_rating FROM heels";
pd.read_sql(query, conn)

   average_rating
0        3.744444

In [37]:
# count
query="SELECT SUM(ratings_count) AS total_ratings FROM heels";
pd.read_sql(query, conn)

   total_ratings
0            141

In [39]:
# group by category and averge
query="SELECT category, AVG(initial_price) AS avg_price FROM heels GROUP BY category";
pd.read_sql(query, conn)

  category    avg_price
0    heels  2564.666667

In [40]:
# step 5 top category product having highest rating
query="SELECT title, rating FROM heels ORDER BY rating DESC LIMIT 1";
pd.read_sql(query, conn)

     title  rating
0  FOOTONS     5.0

In [41]:
# Top 3 Most Expensive Products
query="SELECT title, initial_price FROM heels ORDER BY initial_price DESC LIMIT 3;"
pd.read_sql(query, conn)

           title  initial_price
0  Bruno Manetti         3999.0
1  Bruno Manetti         3999.0
2        FOOTONS         3199.0

In [42]:
# top 3 rated products
query="SELECT title, ratings_count FROM heels ORDER BY ratings_count DESC LIMIT 3";
pd.read_sql(query, conn)

        title  ratings_count
0       TRASE             39
1  DressBerry             34
2       Anouk             25

In [43]:
# Step 6 Use Cases

# Products with Highest Discount
query="SELECT title, discount FROM heels ORDER BY discount DESC LIMIT 5";
pd.read_sql(query, conn)

           title  discount
0  Bruno Manetti      65.0
1  Bruno Manetti      63.0
2         Brauch      62.0
3          Anouk      60.0
4        FOOTONS      55.0

In [44]:
# Products with No Ratings
query="SELECT title, rating, ratings_count FROM heels WHERE ratings_count = 0";
pd.read_sql(query, conn)

    title  rating  ratings_count
0  Brauch     0.0              0

In [45]:
# duplicates count
query="SELECT title, COUNT(*) AS duplicate_count FROM heels GROUP BY title HAVING COUNT(*) > 1";
pd.read_sql(query, conn)

           title  duplicate_count
0  Bruno Manetti                2

In [46]:
# Step 7: Data Validation and Quality Checks
# check for null values
query="SELECT * FROM heels WHERE rating IS NULL OR initial_price IS NULL OR category IS NULL";
pd.read_sql(query, conn)

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [47]:
# Count Missing Discounts
query="SELECT COUNT(*) AS missing_discount FROM heels WHERE discount IS NULL";
pd.read_sql(query, conn)

   missing_discount
0                 2

In [51]:
# row count
print("CSV rows:", len(df))

CSV rows: 9

In [52]:
# Final Conclusion

# 1. SQL queries were successfully executed using SQLite in Jupyter Notebook.
# 2. Filtering and aggregation helped analyze ratings, discounts, and pricing.
# 3. Data validation queries identified missing and duplicate records.
# 4. Business queries provided useful product insights.
# 5. The notebook demonstrates practical SQL-based sales data analysis.